version: '3.9'

services:
  catalog:
    build: ./catalog-svc
    ports:
      - "6543:5000"
    volumes:
      - ./catalog-svc:/root/app

  shop-front-svc:
    build: ./shop-front-svc
    volumes:
      - ./shop-front-svc:/root/app
    ports:
      - "6544:5000"
    
  product-admin:
    build: ./product-admin-svc
    ports:
      - "6545:5000"
    volumes:
      - ./product-admin-svc:/root/app

  gateway:
    image: nginx:latest
    ports:
      - "85:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  catalog-db:
    image: redis
    ports:
      - "6379:6379"
